// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBupdETNH25JjzdTgr3jv7qy3fIhdj__64',
    appId: '1:223355004076:web:169a0d3a4184923001ab09',
    messagingSenderId: '223355004076',
    projectId: 'fir-crashlyticsapp-8eb04',
    authDomain: 'fir-crashlyticsapp-8eb04.firebaseapp.com',
    storageBucket: 'fir-crashlyticsapp-8eb04.appspot.com',
    measurementId: 'G-G9W1KEY8CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZbINqdbBu1vAACt43egCt3_Vz1RPC36w',
    appId: '1:223355004076:android:379476a2da81a16e01ab09',
    messagingSenderId: '223355004076',
    projectId: 'fir-crashlyticsapp-8eb04',
    storageBucket: 'fir-crashlyticsapp-8eb04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc-OJ661weeTRrnWSWonBUzuhkYev6wrs',
    appId: '1:223355004076:ios:0bf1ae47fe6510ce01ab09',
    messagingSenderId: '223355004076',
    projectId: 'fir-crashlyticsapp-8eb04',
    storageBucket: 'fir-crashlyticsapp-8eb04.appspot.com',
    iosBundleId: 'com.example.firebaseCrashlyticsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc-OJ661weeTRrnWSWonBUzuhkYev6wrs',
    appId: '1:223355004076:ios:157557cf2005e89801ab09',
    messagingSenderId: '223355004076',
    projectId: 'fir-crashlyticsapp-8eb04',
    storageBucket: 'fir-crashlyticsapp-8eb04.appspot.com',
    iosBundleId: 'com.example.firebaseCrashlyticsApp.RunnerTests',
  );
}
